package com.example.jijipos;

import android.content.Context;
import androidx.test.core.app.ApplicationProvider;
import androidx.test.ext.junit.runners.AndroidJUnit4;

import com.example.jijipos.database.AppDatabase;
import com.example.jijipos.database.entity.Business;
import com.example.jijipos.database.entity.User;
import com.example.jijipos.repository.UserRepository;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

@RunWith(AndroidJUnit4.class)
public class DatabaseIntegrationTest {

    private UserRepository userRepository;
    private AppDatabase db;

    @Before
    public void setUp() {
        Context context = ApplicationProvider.getApplicationContext();
        userRepository = new UserRepository(context);
        db = AppDatabase.getInstance(context);
    }

    @Test
    public void testUserIntersectionAndRetrieval() throws InterruptedException {
        final CountDownLatch latch = new CountDownLatch(1); // Reduced countdown to 1 since execution is linear

        // 1. Create a dummy parent business profile
        Business mockBusiness = new Business(
                "Juma Retail Store",
                "Dar es Salaam",
                "0711223344",
                System.currentTimeMillis()
        );

        // Run the sequence inside a background executor to accommodate Room blocking rules
        Executors.newSingleThreadExecutor().execute(() -> {
            // Insert parent record and capture the valid ID generated by SQLite
            long realBusinessId = db.businessDao().insertBusiness(mockBusiness);

            // 2. Map the valid business ID to our dummy cashier entity profile
            User mockUser = new User(
                    "Baraka Juma",
                    "0712345678",
                    "hashed_password_123",
                    "CASHIER",
                    realBusinessId
            );

            // 3. STEP A: Insert user account record into the database
            userRepository.insertUser(mockUser, newId -> {
                assertNotNull("User ID insertion failed", newId);

                // STEP B: Nest the lookup inside the success callback so it executes *after* insertion finishes
                userRepository.getUserByPhone("0712345678", fetchedUser -> {
                    assertNotNull("Could not find user by phone number after insertion", fetchedUser);
                    assertEquals("Baraka Juma", fetchedUser.getFullName());
                    assertEquals("CASHIER", fetchedUser.getRole());

                    latch.countDown(); // Let the test thread know the entire sequence passed safely
                });
            });
        });

        // Block test execution framework thread for up to 3 seconds until asynchronous sequence finishes
        boolean success = latch.await(3, TimeUnit.SECONDS);
        assertTrue("Database background operation timed out or crashed!", success);
    }
}